#!/bin/bash

./bin/create-symlinks
./bin/bashrc.sh
if [ $(which vim) ]; then 
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
